name: Publish github package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      # npm
      # - name: Setup npm .npmrc
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"
      #     registry-url: "https://registry.npmjs.org"

      - name: Authenticate with the npm Registry
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm run publish

      # Github packages
      # - name: Setup Github packages .npmrc
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"
      #     registry-url: "https://npm.pkg.github.com"

      - name: Authenticate with the GitHub Package Registry
        run: echo "//npm.pkg.github.com:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Github packages
        run: npm run publish
